---
- name: install docker engine
  hosts: all
  become: yes
  tasks:
  - name: install docker engine
    shell: |
           sudo apt-get install -y \
           apt-transport-https \
           ca-certificates \
           curl \
           gnupg-agent \
           software-properties-common
           curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
           sudo add-apt-repository \
           "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
           sudo apt-get update
           sudo apt-get install -y docker-ce docker-ce-cli containerd.io
           sudo apt-get clean
           cat <<EOF | sudo tee /etc/docker/daemon.json
           {
             "exec-opts": ["native.cgroupdriver=systemd"],
             "log-driver": "json-file",
             "log-opts": {
               "max-size": "100m"
             },
             "storage-driver": "overlay2"
           }
           EOF
           sudo mkdir -p /etc/systemd/system/docker.service.d
           sudo systemctl daemon-reload
           sudo systemctl restart docker
           sudo systemctl enable docker
    register: docker
  - debug: msg="{{ docker.stdout_lines }}"
...
